# Generated by Django 5.0.6 on 2024-10-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0019_alter_player_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='socket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
